### ISSUE TITLE
download_shape function improvements

### ISSUE THREAD

**Issue by camroach87** [AU-BURGr/ozdata#2]
Few issues to consider

* No checks atm to see if there is a shape file present. Crashes if no shape file in zip. Should add a warning.
* Add a file size warning if zip greater than some threshold size.
* A temporary cache folder is created and deleted in the working directory to store zipped/unzipped files. Should probably use a different randomised name for the temporary directory in case user has a cache file that they want to keep.

**Comment by adamhsparks** [comment]
You could use `tempdir()` for your storing zipped unzipped files?

Otherwise, using `rappdirs` could also be a solution to avoid clobbering files/directories in the users' normal working directories.

**Comment by camroach87** [comment]
Jeff's added the tempdir() and tempfile(). I'll leave this issue up for the other items
